#!/usr/bin/env bash

set -e


function die() { echo "$*" 1>&2 ; exit 1; }


function usage () {
    echo "Usage: ./install [-b]"
    echo ""
    echo "Optional arguments:"
    echo "  -b, --brew              Install brew and the dependencies from there"
    echo "  -i, --install           Install extra packages"
    exit 0;
}


BREW=false
INSTALL=false

while getopts "b-:" OPT; do
    if [[ "$OPT" == "-" ]]; then
        OPT="${OPTARG%%=*}"
        OPTARG="${OPTARG#$OPT}"
        OPTARG="${OPTARG#=}"
    fi

    case "$OPT" in
        b | brew ) BREW=true ;;
        i | install ) INSTALL=true ;;
        h | help ) usage ;;
        ? |??* ) die "Unknown option: $OPT" ;;
    esac
done

# Install brew if not installed
if [[ ! -f "${HOME}/.linuxbrew/bin/brew" && ! -f "/home/linuxbrew/.linuxbrew/bin/brew" && ${BREW} == "true" ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" | tee /tmp/brew_install.log
fi

# Source homebrew
if [ -f "${HOME}/.linuxbrew/bin/brew" ]; then
    eval $(${HOME}/.linuxbrew/bin/brew shellenv)
elif [ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]; then
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
fi

if [[ ${BREW} == "true" ]]; then
    brew install gcc zsh git fortune cowsay socat pyenv
    CC=$(brew --prefix gcc)/bin/gcc-11 pyenv install -s 3.10.1
    pyenv rehash
    pyenv global 3.10.1

    if command -v pyenv &> /dev/null; then
        export PYENV_ROOT="$HOME/.pyenv"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
    fi
fi

if [[ ${INSTALL} == "true" ]]; then
    DISPLAY= pip install config/pip_requirements.txt
    curl -sSL https://install.python-poetry.org | python3 -
    pipx install yt-dlp 
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PLUGINS_DIR="${BASEDIR}/plugins"
DOTBOT_DIR="${BASEDIR}/dotbot"
DOTBOT_BIN="${DOTBOT_DIR}/bin/dotbot"

CONFIG_DIR="${BASEDIR}/config"
CONFIG="${CONFIG_DIR}/install.conf.yaml"

export PATH="${HOME}/.local/bin:${PATH}"

cd "${BASEDIR}"
git submodule update --init --recursive 

python3 "${DOTBOT_BIN}" -d "${BASEDIR}" \
    --plugin-dir "${PLUGINS_DIR}/git" \
    --plugin-dir "${PLUGINS_DIR}/pip" \
    -c "${CONFIG}"
