
- defaults:
    link:
        create: true
        relink: true
        force: true
        
- clean: [ '~' ]

- create:
    - ~/.local/bin
    - ~/Documents/Projects
    - ~/Downloads
    
- shell:
    - 
        command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        description: Installing oh-my-zsh
        stdin: true
        stdout: true
        stderr: true
    
- git:
    '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting':
        description: 'oh my zsh syntax highlighting'
        url: https://github.com/zsh-users/zsh-syntax-highlighting.git
        branch: '0.7.1'
        method: clone
    '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
        description: 'oh my zsh autosuggestions'
        url: https://github.com/zsh-users/zsh-autosuggestions
        branch: 'v0.6.4'
        method: clone
    '~/.oh-my-zsh/custom/themes/powerlevel10k':
        description: 'Power level 10k theme'
        url: https://github.com/romkatv/powerlevel10k.git
        branch: 'v1.14.6'
        method: clone
        
- link:
    ~/.zshrc: files/zshrc
    ~/.zshenv: files/zshenv
    ~/.bashrc: files/bashrc
    ~/.local/share/shell: files/shell
    ~/.profile: files/profile
    ~/.bash_profile: files/bash_profile
    ~/.local/bin/gpg-agent-relay: files/gpg-agent-relay
    ~/.gitconfig: files/gitconfig
    ~/.gitignore: files/gitignore
    ~/.latexmkrc: files/latexmkrc
    
- shell:
    - chmod 755 ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    - [curl "https://bootstrap.pypa.io/get-pip.py" | python3, Installing local pip]
    - [bash ./scripts/install_cowsay.sh, Installing cowsay]

- pip:
    file: 'config/pip_requirements.txt'

- pipx:
    file: 'config/pipx_requirements.txt'
                        
                                