
- defaults:
    link:
        create: true
        relink: true
        force: true
        
# - clean: [ '~' ]

- create:
    - ~/.local/bin
    - ~/.ssh
    - ~/Documents/Projects
    - ~/Downloads
        
- link:
    ~/Documents/PowerShell/config.omp.json: pwsh/config.omp.json
    ~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1: pwsh/Microsoft.PowerShell_profile.ps1
    ~/.gitignore: files/gitignore
    ~/.gitconfig: files/gitconfig
    ~/.gitconfig-local: files/gitconfig-windows
    ~/.latexmkrc: files/latexmkrc.pl
    ~/.gdbinit: files/gdbinit
    
- shell:
    - 
        command: pwsh ./scripts/install_scoop.ps1
        description: Installing scoop
        stdin: true
        stdout: true
        stderr: true
    - scoop install git python nodejs-lts cmake rust fd ripgrep


- pip:
    file: 'config/pip_requirements.txt'

- pipx:
    file: 'config/pipx_requirements.txt'


