
- defaults:
  link:
    create: true
    relink: true

- clean: [ '~' ]

- create:
  - ~/.local/bin

- shell:
  - [sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)", Installing oh-my-zsh]

- git:
  '~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting':
    description: 'oh my zsh syntax highlighting'
    url: https://github.com/zsh-users/zsh-syntax-highlighting.git
    branch: '0.7.1'
  '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions':
    description: 'oh my zsh autosuggestions'
    url: https://github.com/zsh-users/zsh-autosuggestions
    branch: 'v0.6.4'

- link:
  ~/.zshrc: zshrc
  ~/.zshenv: zshenv
  ~/.bashrc: bashrc
  ~/.local/bin/gpg-agent-relay: gpg-agent-relay

- shell:
  - chmod 755 ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  - [curl "https://bootstrap.pypa.io/get-pip.py" | python3, Installing local pip]

- pipx:
  file: 'config/pipx_requirements.txt'
  stdout: true
  stderr: true

