format="""
$all\
$fill\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

command_timeout = 2000

[[battery.display]]
threshold = 60

[fill]
symbol = " "

[shell]
disabled = false

[time]
format = '[$time]($style) '
disabled = false

[git_status]
ignore_submodules = true

[hostname]
ssh_only = false

[username]
show_always = true
